# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tuio-ruby}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["aberant"]
  s.date = %q{2010-01-17}
  s.email = %q{qzzzq1@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "Rakefile",
     "examples/tuio_dump.rb",
     "lib/tuio-ruby.rb",
     "lib/tuio-ruby/core_ext/float.rb",
     "lib/tuio-ruby/core_ext/object.rb",
     "lib/tuio-ruby/tuio_client.rb",
     "lib/tuio-ruby/tuio_container.rb",
     "lib/tuio-ruby/tuio_cursor.rb",
     "lib/tuio-ruby/tuio_cursor_parameter.rb",
     "lib/tuio-ruby/tuio_object.rb",
     "lib/tuio-ruby/tuio_object_parameter.rb",
     "lib/tuio-ruby/tuio_parameter.rb",
     "lib/tuio-ruby/tuio_point.rb"
  ]
  s.homepage = %q{http://github.com/aberant/tuio-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{tuio-ruby}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{library to interface with TUIO protocol}
  s.test_files = [
    "spec/integration/tuio_event_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/tuio_cursor_parameter_spec.rb",
     "spec/unit/tuio_cursor_spec.rb",
     "spec/unit/tuio_object_parameter_spec.rb",
     "spec/unit/tuio_object_spec.rb",
     "spec/unit/tuio_parameter_spec.rb",
     "spec/unit/tuio_point_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<osc-ruby>, [">= 0.6.2"])
    else
      s.add_dependency(%q<osc-ruby>, [">= 0.6.2"])
    end
  else
    s.add_dependency(%q<osc-ruby>, [">= 0.6.2"])
  end
end

